apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:  
      node-sample-api: api
  template:
    metadata:
      labels: 
        node-sample-api: api
    spec:
      containers:
      - name: sample-api-container 
        image: creed93/node-sample-api:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: api-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    node-sample-api: api 
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002
    

